#Eureka Client Configuration
eureka:
  instance:
    ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultzone: http://localhost:8761/eureka
#Exception messages
user:
  name:
    mandatory: Name is mandatory
  email:
    invalid: Please enter a valid email
  password:
    size: Password must be between 8 and 20 characters

